### ISSUE TITLE
CUDA error: CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by Xnhyacinth** [FFY0/AdaKV#6]
Great work! 
But I have the following bug in the reproduction process.
Error is: `RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`

How can I solve it?

This only occurs in multi-GPU scenarios, single GPU is WORK!

**Comment by FFY0** [comment]
Thank you for reporting this issue!

Could you provide more detailed error information, such as the full error traceback? This will help us pinpoint the exact cause of the problem. Additionally, sharing details about your environment (PyTorch version, CUDA version, and how you're handling multi-GPU execution) would be very helpful for debugging.

Additionally, the NVIDIA [kvpress](https://github.com/NVIDIA/kvpress) [custom kvpress](https://github.com/FFY0/AdaKV-in-NVIDIA-kvpress) repository provides a more tidy implementation. You might want to try their solution as well.

**Comment by Xnhyacinth** [comment]
That one I finished testing with a single gpu, but I found llama3.1-8B to be slightly normal, but why does llama3-8b generate all this repetitive meaningless content, with the end result not even exceeding 1

![Image](https://github.com/user-attachments/assets/382755e2-4994-47de-bea2-1ae5fb53eba3)

Of course this problem also happens in kvpress, how do I need to improve it?

**Comment by FFY0** [comment]
Hi, I noticed that you also encountered this issue in `kvpress` implementation. I think this issue stems more from the characteristics of Llama-3-8B. I will assist you in resolving this problem under the issues of kvpress https://github.com/NVIDIA/kvpress/issues/56.

**Comment by Xnhyacinth** [comment]
Thanks a lot!

**Comment by Xnhyacinth** [comment]
@FFY0 hi, I set the length to 7950, but “full_kv: 5.35” on hotpotqa and only “full_kv: 3.14” on narrativeqa.

**Comment by Xnhyacinth** [comment]
> [@FFY0](https://github.com/FFY0) hi, I set the length to 7950, but “full_kv: 5.35” on hotpotqa and only “full_kv: 3.14” on narrativeqa.

It might have been a weighting issue, I replaced it with 'unsloth__llama-3-8b-Instruct' and it works fine now!

Also, 3.x model is normal!

Thanks a lot!
